export const ADDRESSES = {
  WCTC: "0xBFd5542a97E96D8F2E2D1A39E839c7A15bA731E1",
  CreditVault: "0x47bdf18319B5068d88E80C8edFD075d63470e222",
  MockStaking: "0x5e3Fe22590C61818e13CB3F1f75a809A1b014BC3",
  MockLendingPool: "0xea927CE7A20F957ECDDe6888ecfDa79f43e6197F",
  MockAMM: "0x96784C7deCcAc3Fdc86f5988f66888eb18359c3F",
  StakingStrategy: "0x70e2FdF55A4314c9ac521f133577CdF4C297DB3b",
  LendingStrategy: "0x87FFB21B290B01D7cb8B696dFBFCe692587aAA8D",
  LPStrategy: "0x0767Bc9c393967c21F7800C5C806Fdc65C5C77bC",
} as const;

export const CREDIT_VAULT_ABI = [
  { type: "constructor", inputs: [{ name: "_wctc", type: "address" }], stateMutability: "nonpayable" },
  { type: "receive", stateMutability: "payable" },
  // --- ERC-20 / ERC-4626 views ---
  { type: "function", name: "name", inputs: [], outputs: [{ name: "", type: "string" }], stateMutability: "view" },
  { type: "function", name: "symbol", inputs: [], outputs: [{ name: "", type: "string" }], stateMutability: "view" },
  { type: "function", name: "decimals", inputs: [], outputs: [{ name: "", type: "uint8" }], stateMutability: "view" },
  { type: "function", name: "totalSupply", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "balanceOf", inputs: [{ name: "account", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "asset", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "totalAssets", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "convertToShares", inputs: [{ name: "assets", type: "uint256" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "convertToAssets", inputs: [{ name: "shares", type: "uint256" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "previewDeposit", inputs: [{ name: "assets", type: "uint256" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "previewWithdraw", inputs: [{ name: "assets", type: "uint256" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "previewRedeem", inputs: [{ name: "shares", type: "uint256" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "maxDeposit", inputs: [{ name: "", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "maxWithdraw", inputs: [{ name: "owner", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "maxRedeem", inputs: [{ name: "owner", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  // --- CreditVault custom views ---
  { type: "function", name: "sharePrice", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "getAllocations", inputs: [], outputs: [{ name: "staking", type: "uint256" }, { name: "lending", type: "uint256" }, { name: "lp", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "getPendingRewards", inputs: [], outputs: [{ name: "staking", type: "uint256" }, { name: "lending", type: "uint256" }, { name: "lp", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "stakingWeight", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "lendingWeight", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "lpWeight", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "totalHarvested", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "lastHarvestBlock", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "owner", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "keeper", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "wctc", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "stakingStrategy", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "lendingStrategy", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "lpStrategy", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  // --- CTC deposit/withdraw (native) ---
  { type: "function", name: "depositCTC", inputs: [{ name: "receiver", type: "address" }], outputs: [{ name: "shares", type: "uint256" }], stateMutability: "payable" },
  { type: "function", name: "withdrawCTC", inputs: [{ name: "assets", type: "uint256" }, { name: "receiver", type: "address" }, { name: "_owner", type: "address" }], outputs: [{ name: "shares", type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "redeemCTC", inputs: [{ name: "shares", type: "uint256" }, { name: "receiver", type: "address" }, { name: "_owner", type: "address" }], outputs: [{ name: "assets", type: "uint256" }], stateMutability: "nonpayable" },
  // --- ERC-4626 WCTC deposit/withdraw ---
  { type: "function", name: "deposit", inputs: [{ name: "assets", type: "uint256" }, { name: "receiver", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "withdraw", inputs: [{ name: "assets", type: "uint256" }, { name: "receiver", type: "address" }, { name: "owner", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "redeem", inputs: [{ name: "shares", type: "uint256" }, { name: "receiver", type: "address" }, { name: "owner", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "nonpayable" },
  // --- Admin ---
  { type: "function", name: "harvest", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "rebalance", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setWeights", inputs: [{ name: "_staking", type: "uint256" }, { name: "_lending", type: "uint256" }, { name: "_lp", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setStrategies", inputs: [{ name: "_staking", type: "address" }, { name: "_lending", type: "address" }, { name: "_lp", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setKeeper", inputs: [{ name: "_keeper", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "transferOwnership", inputs: [{ name: "newOwner", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  // --- ERC-20 ---
  { type: "function", name: "approve", inputs: [{ name: "spender", type: "address" }, { name: "value", type: "uint256" }], outputs: [{ name: "", type: "bool" }], stateMutability: "nonpayable" },
  { type: "function", name: "allowance", inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "transfer", inputs: [{ name: "to", type: "address" }, { name: "value", type: "uint256" }], outputs: [{ name: "", type: "bool" }], stateMutability: "nonpayable" },
  { type: "function", name: "transferFrom", inputs: [{ name: "from", type: "address" }, { name: "to", type: "address" }, { name: "value", type: "uint256" }], outputs: [{ name: "", type: "bool" }], stateMutability: "nonpayable" },
  // --- Events ---
  { type: "event", name: "DepositedCTC", inputs: [{ name: "sender", type: "address", indexed: true }, { name: "receiver", type: "address", indexed: true }, { name: "assets", type: "uint256", indexed: false }, { name: "shares", type: "uint256", indexed: false }], anonymous: false },
  { type: "event", name: "WithdrawnCTC", inputs: [{ name: "sender", type: "address", indexed: true }, { name: "receiver", type: "address", indexed: true }, { name: "assets", type: "uint256", indexed: false }, { name: "shares", type: "uint256", indexed: false }], anonymous: false },
  { type: "event", name: "Harvested", inputs: [{ name: "stakingReward", type: "uint256", indexed: false }, { name: "lendingReward", type: "uint256", indexed: false }, { name: "lpReward", type: "uint256", indexed: false }, { name: "total", type: "uint256", indexed: false }], anonymous: false },
  { type: "event", name: "Rebalanced", inputs: [{ name: "stakingAlloc", type: "uint256", indexed: false }, { name: "lendingAlloc", type: "uint256", indexed: false }, { name: "lpAlloc", type: "uint256", indexed: false }], anonymous: false },
  { type: "event", name: "Deposit", inputs: [{ name: "sender", type: "address", indexed: true }, { name: "owner", type: "address", indexed: true }, { name: "assets", type: "uint256", indexed: false }, { name: "shares", type: "uint256", indexed: false }], anonymous: false },
  { type: "event", name: "Withdraw", inputs: [{ name: "sender", type: "address", indexed: true }, { name: "receiver", type: "address", indexed: true }, { name: "owner", type: "address", indexed: true }, { name: "assets", type: "uint256", indexed: false }, { name: "shares", type: "uint256", indexed: false }], anonymous: false },
  { type: "event", name: "Transfer", inputs: [{ name: "from", type: "address", indexed: true }, { name: "to", type: "address", indexed: true }, { name: "value", type: "uint256", indexed: false }], anonymous: false },
  { type: "event", name: "Approval", inputs: [{ name: "owner", type: "address", indexed: true }, { name: "spender", type: "address", indexed: true }, { name: "value", type: "uint256", indexed: false }], anonymous: false },
  // --- Errors ---
  { type: "error", name: "OnlyOwner", inputs: [] },
  { type: "error", name: "OnlyKeeper", inputs: [] },
  { type: "error", name: "InvalidWeights", inputs: [] },
  { type: "error", name: "StrategiesNotSet", inputs: [] },
  { type: "error", name: "TransferFailed", inputs: [] },
] as const;

export const WCTC_ABI = [
  { type: "function", name: "deposit", inputs: [], outputs: [], stateMutability: "payable" },
  { type: "function", name: "withdraw", inputs: [{ name: "amount", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "balanceOf", inputs: [{ name: "account", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "approve", inputs: [{ name: "spender", type: "address" }, { name: "value", type: "uint256" }], outputs: [{ name: "", type: "bool" }], stateMutability: "nonpayable" },
  { type: "function", name: "allowance", inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "totalSupply", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "name", inputs: [], outputs: [{ name: "", type: "string" }], stateMutability: "view" },
  { type: "function", name: "symbol", inputs: [], outputs: [{ name: "", type: "string" }], stateMutability: "view" },
  { type: "function", name: "decimals", inputs: [], outputs: [{ name: "", type: "uint8" }], stateMutability: "view" },
] as const;
